apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: platform-config
  namespace: argocd

spec:
  project: platform
  source:
    repoURL: git@github.com:eusouodaniel/rocketseat.platform-apps.git
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
