apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: read-pod
  namespace: default

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: read-pod-binding
  namespace: default

subjects:
  - kind: Group
    name: group-rocketseat
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-pod
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: read-ns

rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: read-ns-binding

subjects:
  - kind: Group
    name: group-rocketseat
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRoleRole
  name: read-ns
  apiGroup: rbac.authorization.k8s.io