apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: read-pod
  namespace: default

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: read-pod-binding
  namespace: default

subjects:
  - kind: User
    name: rocketseat-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-pod
  apiGroup: rbac.authorization.k8s.io