apiVersion: v1
kind: ServiceAccount

metadata:
  name: sa-default
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: read-sa-pod
  namespace: default

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: read-sa-pod-binding
  namespace: default

subjects:
  - kind: ServiceAccount
    name: sa-default
roleRef:
  kind: Role
  name: read-sa-pod
  apiGroup: rbac.authorization.k8s.io
