kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: app
  name: pod-failure-app-ts-2
spec:
  selector:
    namespaces:
    - app
    labelSelectors:
      api: app-ts
  mode: all
  value: '20'
  action: pod-failure
  duration: 60s