apiVersion: v1
kind: LimitRange

metadata:
  name: ns-limit-range
  namespace: app

spec:
  limits:
  - default:
      cpu: "100m"
      memory: "128Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: 1
      memory: 1Gi
    min:
      cpu: "60m"
      memory: "64Mi"
    type: Container