apiVersion: apps/v1
kind: ResourceQuota

metadata:
  name: ns-quota
  namespace: app

spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
    pods: "20"
