apiVersion: v1
kind: Secret

metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}

type: Opaque

data:
  {{- range $key, $val := .Values.appSecretEnv }}
  {{ $key }}: "{{ $val }}"
  {{- end }}