apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass

metadata:
  name: envoy

spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: main-gateway
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer-prod

spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.eusouodaniel.xyz"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.eusouodaniel.xyz"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-eusoudaniel-domain-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: tls-redirect
  namespace: infra

spec:
  parentRefs:
    - name: main-gateway
      namespace: infra
      sectionName: http
  hostnames:
    - "*.eusouodaniel.xyz"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: app-ts-route
  namespace: app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: app-ts.eusoudaniel.xyz

spec:
  parentRefs:
    - name: main-gateway
      namespace: infra
      sectionName: https
  hostnames:
    - "app-ts.eusouodaniel.xyz"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
      - name: app-ts-svc
        port: 80
          